# dependencies fixed for reproducibility
name: tudat-examples
channels:
  - conda-forge
  - tudat-team/label/dev
  - tudat-team
dependencies:
  - tudatpy
  - numpy<2.0
  - pygmo
  - ipython
  - ipykernel
  - nbconvert # for create_script.py utility
  - tqdm # for create_script.py utility
