# dependencies fixed for reproducibility
name: tudat-examples
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudatpy=0.9
  - numpy<2.0
  # - pygmo # incompatible boost for tudatpy v0.9.0
  - ipython
  - ipykernel
  - nbconvert # for create_script.py utility
  - tqdm # for create_script.py utility
