name: Sync tudat-space submodule
on:
    push:
      branches:
        - master
    workflow_dispatch:

env:
  TARGET_OWNER: tudat-team
  TARGET_REPO: tudat-space

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_OWNER }}/${{ env.TARGET_REPO }}
          token: ${{ secrets.GH_PAT }}
          ref: develop

      - name: Update submodule commit
        run: |
            git submodule update --init --recursive
            git submodule update --recursive --remote

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update submodule to ${{ github.event.after }}"